# Site settings
title: artist portfolio
email: artist@email
description: Software Engineer // Designer // Architect


# Build settings
markdown: kramdown
permalink: pretty

port: 3000

include: ['_includes/work']

sass:
  sass_dir: assets/css
  style: :compressed
